# Generated by Django 4.2.6 on 2023-10-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_of_lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='start_date',
        ),
    ]
