# Generated by Django 4.2.6 on 2023-10-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_of_lessons', '0002_remove_product_category_remove_product_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaccess',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAccess',
        ),
    ]
